# Generated by Django 5.2.1 on 2025-11-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_userprofile_user'),
        ('quiz', '0004_update_questionupload_for_pdf'),
    ]

    operations = [
    ]
