# Generated by Django 5.2.1 on 2025-11-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_merge_20251109_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Question Upload', 'verbose_name_plural': 'Question Uploads'},
        ),
    ]
