# Generated by Django 5.2.1 on 2025-11-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_descriptive_questions'),
        ('quiz', '0006_alter_questionupload_options'),
    ]

    operations = [
    ]
