# Generated by Django 5.2.1 on 2025-11-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_merge_20251111_2223'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='descriptivequestion',
            new_name='quiz_descri_subject_124e2a_idx',
            old_name='quiz_descri_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequestion',
            new_name='quiz_descri_is_acti_2d4736_idx',
            old_name='quiz_descri_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequiz',
            new_name='quiz_descri_institu_f94914_idx',
            old_name='quiz_descri_quiz_inst_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequiz',
            new_name='quiz_descri_subject_3239b7_idx',
            old_name='quiz_descri_quiz_subj_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequizattempt',
            new_name='quiz_descri_user_id_5fd4aa_idx',
            old_name='quiz_descri_attempt_user_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequizattempt',
            new_name='quiz_descri_quiz_id_84ef29_idx',
            old_name='quiz_descri_attempt_quiz_idx',
        ),
        migrations.RenameIndex(
            model_name='descriptivequizattempt',
            new_name='quiz_descri_status_a8c20e_idx',
            old_name='quiz_descri_attempt_stat_idx',
        ),
    ]
